baseURL = 'https://pegana-cat.github.com/'
languageCode = 'cat'
title = 'Pegana.cat'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true
	[markup.goldmark.parser]
		wrapStandAloneImageWithinParagraph = false
		[markup.goldmark.parser.attribute]
			block = true
[permalinks]
  content = '/:slug/:title/'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'
